local ADDON_NAME, NS = ...

NS = NS or {}

NS.ADDON_NAME = ADDON_NAME
NS.App = NS.App or CreateFrame("Frame")
NS.Const = NS.Const or {}
NS.Util = NS.Util or {}
NS.Database = NS.Database or {}
NS.Discovery = NS.Discovery or {}
NS.RunLogic = NS.RunLogic or {}
NS.UI = NS.UI or {}
NS.UI.history = NS.UI.history or {}
NS.Settings = NS.Settings or {}
NS.Tests = NS.Tests or {}
NS.Private = NS.Private or {}
NS.Debug = NS.Debug or {}

local UI = NS.UI
UI.timerFrame = UI.timerFrame or nil
UI.bossFrame = UI.bossFrame or nil
UI.timerText = UI.timerText or nil
UI.killCountText = UI.killCountText or nil
UI.historyButton = UI.historyButton or nil
UI.st = UI.st or nil
UI.cols = UI.cols or nil
UI.data = UI.data or nil
UI.rowByBossKey = UI.rowByBossKey or nil
UI._modelWidth = UI._modelWidth or 40
UI._pbWidth = UI._pbWidth or 80
UI._splitWidth = UI._splitWidth or 80
UI._deltaWidth = UI._deltaWidth or 60
UI._rightInset = UI._rightInset or 26
UI._topInset = UI._topInset or 26
UI._bottomInset = UI._bottomInset or 34
UI._colGrips = UI._colGrips or nil
UI._colDrag = UI._colDrag or nil
UI.totalFrame = UI.totalFrame or nil
UI.totalBg = UI.totalBg or nil
UI.totalPB = UI.totalPB or nil
UI.totalSplit = UI.totalSplit or nil
UI.totalDelta = UI.totalDelta or nil
UI.timerDeltaText = UI.timerDeltaText or nil
UI.timerToastBg = UI.timerToastBg or nil
UI.resizeGrip = UI.resizeGrip or nil
UI._timerResizeGrip = UI._timerResizeGrip or nil
UI.history.frame = UI.history.frame or nil
UI.history.searchBox = UI.history.searchBox or nil
UI.history.tierDropDown = UI.history.tierDropDown or nil
